core/blog/urls.py
from django.urls import path
from django.views.generic import TemplateView, RedirectView
from . import views

app_name = 'blog'

urlpatterns = [
    # path('', TemplateView.as_view(template_name='index.html', extra_context={'name': 'Arian'}), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('go-to-index/', RedirectView.as_view(pattern_name='blog:index'), name='redirect-to-index'),
    path('go-to-index/', views.RedirectToIndex.as_view(), name='redirect-to-index'),
    path('post/', views.PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/create/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/edit', views.PostEditView.as_view(), name='post-edit'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


class UserManager(BaseUserManager):
    """
    Custom user manager that allows you to create new users
    """

    def create_user(self, email, password, **extra_fields):
        """
        Creates and saves a new user
        """
        if not email:
            raise ValueError(_('Email is required'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Creates and saves a new superuser
        """
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model that supports using email instead of username.
    """
    email = models.EmailField(max_length=200, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    # is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


class Profile(models.Model):
    image = models.ImageField(blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'.strip()

    def __str__(self):
        return self.get_full_name() if self.get_full_name() else self.user.email

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Getting user model object
User = get_user_model()


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    """
    This is a class to define posts for blog app
    """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    image = models.ImageField(blank=True, null=True)
    author = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.ManyToManyField('Category')
    status = models.CharField(choices=STATUS_CHOICES, default='draft', max_length=50)
    published_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = 'image', 'author'

core/accounts/views.py
from django.shortcuts import render

# Create your views here.

core/blog/views.py
from django.views.generic import TemplateView, RedirectView, ListView, DetailView, FormView, CreateView, UpdateView, \
    DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import PostCreateForm
from .models import Post


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Arian'
        return context


class RedirectToIndex(RedirectView):
    permanent = False
    query_string = False
    pattern_name = 'blog:index'


class PostListView(PermissionRequiredMixin, ListView):
    permission_required = 'blog.view_post'
    # model = Post
    queryset = Post.published.all()
    template_name = 'blog/posts.html'  # Default -> blog/post_list.html
    context_object_name = 'posts'  # Default -> object_list
    paginate_by = 2
    ordering = '-id'

    # def get_queryset(self):
    #     posts = Post.published.all()
    #     return posts


class PostDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'blog.view_post'
    queryset = Post.published.all()
    context_object_name = 'post'


# class PostCreateView(FormView):
#     template_name = 'blog/create.html'
#     form_class = PostCreateForm
#     success_url = '/blog/post/'
#
#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'blog.create_post'
    # fields = '__all__'
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/create.html'

    # success_url = '/blog/post/'  # Default -> current post url -> blog/post/5

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'blog.change_post'
    model = Post
    form_class = PostCreateForm
    template_name = 'blog/create.html'


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'blog.delete_post'
    model = Post
    template_name = 'blog/delete.html'
    success_url = '/blog/post/'

core/templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
</body>
</html>

core/templates/blog/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Confirm</button>
</form>
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ post.title }}</title>
</head>
<body>
<h1>{{ post.title }}</h1>
<hr>
<small>{{ post.author }} - {{ post.published_at }}</small>
<p>{{ post.content }}</p>
</body>
</html>

core/templates/blog/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
</head>
<body>
<h1>Blog Post</h1>
{% for post in posts %}
<div>
    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    <div>
        <a href="{% url 'blog:post-edit' pk=post.id %}">Edit</a>
        <a href="{% url 'blog:post-delete' pk=post.id %}">Delete</a>
    </div>
    <p>{{ post.content }}</p>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello {{ name }}</h1>
</body>
</html>